---
title: "Untitled"
author: "Yihao Wang"
date: "2026-03-13"
output: html_document
---

```{r}
# load the data
data <- read.csv("GLB.Ts+dSST.csv", skip = 1)
head(data)
```

```{r}
# plot of the time series
data[data == "***"] <- NA
months <- data[,2:13]
monthly <- as.numeric(t(months))
monthly <- monthly[!is.na(monthly)]
ts_temp <- ts(monthly)
plot(ts_temp,
     main="Monthly Global Temperature Anomaly",
     ylab="Temperature Anomaly (°C)"
     )
```
```{r}
# plot of the differenced time series
ts_season_diff <- diff(ts_temp, lag=12)
plot(ts_season_diff)
```

```{r}
# sample acf of the raw time series
acf(ts_temp, main = "ACF of the Original Series")
# sample acf of the differenced time series
acf(ts_season_diff, main = "ACF of the Differenced Series")
```
```{r}
# stationary test
library(tseries)
adf.test(ts_season_diff, k = 0)
adf.test(ts_season_diff)
pp.test(ts_season_diff)
```
```{r}
# Finding the minimum AIC fitted model
library(astsa) 
aic <- sarima(ts_season_diff,0,0,0,details = FALSE)$fit$aic 
minAICp <- 0 
minAICq <- 0 
for(p in seq(0,10)){ 
  for(q in seq(0,10)){ 
    fit <- sarima(ts_season_diff,p,0,q,details = FALSE) 
    if(fit$fit$aic < aic){ 
      aic <- fit$fit$aic 
      minAICp <- p 
      minAICq <- q 
    } 
  } 
}
minAICp
minAICq
```


```{r}
# automatic model selection
library(forecast)
auto.arima(ts_temp, seasonal = TRUE)
auto.arima(ts_season_diff)
```
```{r}
# model diagnostics
fit1 <- sarima(ts_temp, 3, 1, 3)
fit2 <- sarima(ts_season_diff, 1, 0, 1)
fit3 <- sarima(ts_temp, 1,0,1, 0,1,0, 12)
```

